import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Video-Talk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={'${inter.className} bg-dark-2'}>
        {children}
      </body>
    </html>
  );
}
